# Generated by Django 5.2.17 on 2026-09-20 17:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='currency_symbol',
            field=models.CharField(default='₹', max_length=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='monthly_budget',
            field=models.DecimalField(decimal_places=2, default=Decimal('12000.00'), help_text='Target budget for each calendar month.', max_digits=10),
        ),
    ]
